INSERT INTO db_site.categories (name) VALUES("Antipasto");
INSERT INTO db_site.categories (name) VALUES("Primo piatto");
INSERT INTO db_site.categories (name) VALUES("Secondo piatto");
INSERT INTO db_site.categories (name) VALUES("Contorno");
INSERT INTO db_site.categories (name) VALUES("Dessert");

INSERT INTO db_site.recipes (creation_date, category_id, title, ingredients, preparation_time, portions, text, image) VALUES('2024-01-22', 1, 'Pasta coi peperoni', '100g pasta, 1 cucchiaio di olio, 1 peperone', 30, 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'https://tse1.mm.bing.net/th?id=OIP.IJeIkxjvlv-VAXp9R1VGLgHaE8&pid=Api');
INSERT INTO db_site.recipes (creation_date, category_id, title, ingredients, preparation_time, portions, text, image) VALUES('2024-01-21', 1, 'Pasta con zucchine', '100g pasta, 2 zucchine, formaggio', 25, 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'https://tse4.mm.bing.net/th?id=OIP.p58BtonD-sR_htddYCSL7gHaE7&pid=Api');
INSERT INTO db_site.recipes (creation_date, category_id, title, ingredients, preparation_time, portions, text, image) VALUES('2024-01-08', 2, 'Antipasto di peperoni', '4 peperoni, 100g di olio, origano', 20, 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'https://tse4.mm.bing.net/th?id=OIP.OXY7J89Xq3qDHQ3YRWqTlAHaGL&pid=Api');
INSERT INTO db_site.recipes (creation_date, category_id, title, ingredients, preparation_time, portions, text, image) VALUES('2023-11-06', 5, 'Panna cotta', 'Panna, fragole, caramello', 10, 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'https://tse3.mm.bing.net/th?id=OIP.4oyBSAD7EvwRRTpJ0xfzCAHaE7&pid=Api');
INSERT INTO db_site.recipes (creation_date, category_id, title, ingredients, preparation_time, portions, text, image) VALUES('2023-12-16', 4, 'Patate al forno', 'Patate', 20, 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'https://tse3.mm.bing.net/th?id=OIP.8faRrNEpGBqvWcsYvJDQ5AHaE7&pid=Api');


